healthcare:
  target: dev
  outputs:
    dev:
      type: trino
      method: none
      host: "{{ env_var('TRINO_HOST', 'trino.<HOST>') }}"
      port: 443
      http_scheme: https
      database: iceberg
      schema: demo
      threads: 1
      user: "niels.claeys@dataminded.com"
